# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs at https://scoutapm.com/docs/ruby/configuration#environment-variables for more information.
common: &defaults

  # key: Your Organization key for Scout APM. Found on the settings screen.
  # - Default: none
  key: <%= ::EdifyConfig.scout_apm_key %>

  # log_level: Verboseness of logs.
  # - Default: 'info'
  # - Valid Options: debug, info, warn, error
  log_level: info
  logs_monitor: true
  logs_ingest_key: <%= ::EdifyConfig.scout_apm_logs_ingest_key %>

  # name: Application name in APM Web UI
  # - Default: the application names comes from the Rails or Sinatra class name
  name: edify

  # monitor: Enable Scout APM or not
  # - Default: none
  # - Valid Options: true, false
  monitor: true
  errors_enabled: true
  errors_ignored_exceptions:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
    - ActionController::InvalidAuthenticityToken

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: false
  logs_monitor: false
  errors_enabled: false

test:
  <<: *defaults
  monitor: false
  logs_monitor: false
  errors_enabled: false
